name = "genzai"
account_id = "f374e7e2d001dd43253c8d47182e3882"
main = "functions/worker.js"
compatibility_date = "2026-10-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]
