name = "gen-zai"
account_id = "0f42fca3464aa845060fe38b7774d788"
main = "functions/worker.js"
compatibility_date = "2026-10-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]
